default_platform(:ios)

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Description of what the lane does"
  lane :sign do |options|
    api_key = app_store_connect_api_key(
      key_id: options[:key_id],
      issuer_id: options[:issuer_id],
      key_content: options[:api_key],
      is_key_content_base64: true,
      in_house: false
    )
    match(api_key: api_key, type: 'appstore')
  end
  lane :beta do |options|
    api_key = app_store_connect_api_key(
      key_id: options[:key_id],
      issuer_id: options[:issuer_id],
      key_content: options[:api_key],
      is_key_content_base64: true,
      in_house: false
    )
    increment_build_number({
      build_number: latest_testflight_build_number(api_key: api_key) + 1
    })
    gym()
    pilot()
    slack(
      message: "🚀 New Image Search 🔎 in TF",
      channel: "#marketing_aso_vlad",  # Optional, by default will post to the default channel configured for the POST URL.
      payload: {  # Optional, lets you specify any number of your own Slack attachments.
        "Build Number" => latest_testflight_build_number(api_key: api_key),
      },
      default_payloads: [:git_author, :last_git_commit] # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
            # Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit`, `last_git_commit_hash`.
    )
  end
end